### ISSUE TITLE
Display in CHAIN_REG is messed up

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1189] opened 2019-08-11 17:39 UTC
I am using 2945 build and noticed this when I first installed it. 
![door_issue](https://user-images.githubusercontent.com/13500419/62837451-57d60880-bc24-11e9-99ab-a6224d511a53.jpg)

**Comment by mmunson** [comment] 2019-08-13 07:09
I figured out the problem. I needed to clear out the sponsored by field and it works ok now.

**Comment by BloodStoneBBS** [comment] 2019-08-13 12:58
I've been seeing a very similar issue over here but clearing the sponsored by field doesn't help.
In fact, the last game in the list shows a random number in the thousands.

It's clearly a bug in how the sponsor is displayed.

**Comment by wwiv** [comment] 2019-08-18 04:20
I can't reproduce this one, any exact steps would be helpful. Thanks

**Comment by BloodStoneBBS** [comment] 2019-08-18 13:29
Set CHAIN_REG  = Y in wwiv.ini.
In Chainedit, select user as sponsor,
log in and view doors.
Additional intermittent issue is that last door in list may show random usage number. Even after resetting to 0.

**Comment by BloodStoneBBS** [comment] 2019-08-18 13:36
Example -
Global War has 1 play yet shows 282. Randomly displays random username as sponsor.
 
![Capture](https://user-images.githubusercontent.com/13243281/63225160-63748280-c182-11e9-82ab-33944a992f70.PNG)

**Comment by BloodStoneBBS** [comment] 2019-08-18 13:41
Add sponsor to GLobar War, sponsor name appears twice:
![Capture](https://user-images.githubusercontent.com/13243281/63225318-3b395380-c183-11e9-91e6-bd61415babb0.PNG)

**Comment by BloodStoneBBS** [comment] 2019-08-18 13:45
Cleared registered by on Global War, gap remains in chain edit:
![Capture](https://user-images.githubusercontent.com/13243281/63225348-c87ca800-c183-11e9-93ca-2dae1e25a6ee.PNG)

**Comment by BloodStoneBBS** [comment] 2019-08-18 13:49
Gap after 19 gone now, added Jahmas as registered by on chain. All looking better by just adding/removing/modifying.
![Capture](https://user-images.githubusercontent.com/13243281/63225396-450f8680-c184-11e9-9de8-39b5e1f71534.PNG)

**Comment by BloodStoneBBS** [comment] 2019-08-18 13:58
Now log in remotely - SyncTerm:
![Capture](https://user-images.githubusercontent.com/13243281/63225518-95d3af00-c185-11e9-9524-125aa3dce1bc.JPG)

Demonstrates random plays and adds back space in list.

**Comment by BloodStoneBBS** [comment] 2019-08-18 14:21
Local view of chains look normal

**Comment by wwiv** [comment] 2019-08-18 15:18
Thanks for the screen shots. I tried again but can't put one into the bad state.. How do you go from good state (unregistered), so one with the messed up display?  I tried adding and removing people sponsoring it, bot no luck.

**Comment by BloodStoneBBS** [comment] 2019-08-18 15:25
For me, all I need to do is add or remove a user as Registered By and it occurs. However, it may look fine at times locally, connecting remotely will show something different.
It also seems that it’s possible to add multiple users per line, causing additional gaps.

**Comment by BloodStoneBBS** [comment] 2019-08-20 13:01
Updated to latest build, Now showing random user and plays for one chain.
Registered by shows Available, CE shows random user below. Plays change at random, grew from 2 to 197 over night.

![Capture](https://user-images.githubusercontent.com/13243281/63349317-00b0f180-c310-11e9-980a-8ec6d322d098.JPG)

**Comment by BloodStoneBBS** [comment] 2019-08-20 13:07
Removed all sponsored by and the display looks good with no corruption now but modifying las chain, still shows random user and age limit was oddly set to 57-167 where all others show 0-255. Cannot change age limits on last chain. only lowest number. 0-167

**Comment by BloodStoneBBS** [comment] 2019-08-20 15:20
Just got a good laugh...
In the last two hours, chain # 19 jumped from 197 to 25711.
 19│Global WAR                               │Available            │25711│
 No longer shows Sponsored by Magus.

**Comment by mmunson** [comment] 2019-08-20 17:15
Have we tried regression by looking at prior versions of the code. Maybe some new change broke it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BloodStoneBBS** [comment] 2019-08-20 21:23
I have not.

However, I first noticed it a few years back. Simply thought it was related to the option to allow users to sponsor a chain. Would bet it goes back to early v5 or even 4.30.


________________________________

**Comment by wwiv** [comment] 2019-08-22 05:01
sounds like something is stomping the chain.reg file on your bbs, but I can't make it happen on mine

**Comment by BloodStoneBBS** [comment] 2019-08-22 13:00
So I renamed chain.reg and edited the chains again. Was able to remove all extra lines in chain 19 by entering 0 multiple times until the extra spaces were gone, noted new chains .reg file - identical.
Looked great in  //ce all showed available and 19 reset to 0 plays.
logged in via SyncTerm and 19 once again has multiple blank lines, magus is the sponsor and plays in the hundreds. 
Am going to just delete 19th (chain 18) door.

**Comment by wwiv** [comment] 2019-09-11 03:30
I took a sledge hammer to the chains and replaced it with chains.json in the latest release.  Hopefully that fixes it for good. 

Fixed in https://github.com/wwivbbs/wwiv/commit/bdaa0ca5f0468b92a517fcaf954b995c744f2e1c

**Comment by wwiv** [comment] 2019-09-11 03:31
If anything looks wrong, look in ```data/chains.json``` to see if the file has the garbage data in it.

**Closed as completed by wwiv** 2019-09-11 03:30 UTC
