### ISSUE TITLE
wwiv-server no longer loads crashes --- where's the log file??

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1080] opened 2017-03-29 00:39 UTC
Can not find log file to see if there's an error messge.  WWIV-Server loads and then immediately crashes.

**Comment by wwiv** [comment] 2017-04-02 01:17
there should be a wwivd.log.  Is anything printed?

**Comment by wwiv** [comment] 2017-07-15 15:33
probably from wwiv-server.exe (the C# one).

**Comment by wwiv** [comment] 2018-05-11 17:08
I can't reproduce it, closing as obsolete.

**Closed as completed by wwiv** 2018-05-11 17:08 UTC
Labels: bug, not reproducible, wwivserver/wwivd
