### ISSUE TITLE
bbs.exe crashes when pasting text into new message

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#198] opened 2015-09-14 16:09 UTC
Could be a buffer issue? When pasting a fair amount of text into a new message (standard WWIV editor) bbs.exe crashes.
Windows 7 w32
Subversion Build: 1569  
Telnet Client SyncTerm v0.9.5b - SDL

---

Log Name:      Application
Source:        Application Error
Date:          9/14/2015 7:55:09 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WWIV5
Description:
Faulting application name: bbs.exe, version: 0.0.0.0, time stamp: 0x55f63751
Faulting module name: bbs.exe, version: 0.0.0.0, time stamp: 0x55f63751
Exception code: 0xc0000409
Fault offset: 0x000ef5ba
Faulting process id: 0xf00
Faulting application start time: 0x01d0eefd3d9e73cd
Faulting application path: C:\wwiv\bbs.exe
Faulting module path: C:\wwiv\bbs.exe
Report Id: 9785773d-5af0-11e5-96e2-534e57000000
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-14T14:55:09.000000000Z" />
    <EventRecordID>8164</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WWIV5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55f63751</Data>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55f63751</Data>
    <Data>c0000409</Data>
    <Data>000ef5ba</Data>
    <Data>f00</Data>
    <Data>01d0eefd3d9e73cd</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>9785773d-5af0-11e5-96e2-534e57000000</Data>
  </EventData>
</Event>

**Comment by ericpareja** [comment] 2015-09-15 14:46
Can we have an idea how much text was pasted in?

**Comment by BloodStoneBBS** [comment] 2015-09-15 15:34
Hi Eric, 

Yes. The contents of this file.
http://textfiles.com/bbs/WWIVNEWS/wwiv9101.txt

The first attempt, the BBS crashed in the second paragraph in the text "Soon the 64k limitation of IBM interpreted BASIC became apparent."

The second attempt, the crash was several paragraphs in. Do not recall the text or line.

What is the current limitation on characters and is there a way to prevent a crash when pasting?

**Comment by ericpareja** [comment] 2015-09-16 13:54
Have you tried using //LOAD then Post?

**Comment by wwiv** [comment] 2015-09-19 20:56
man this is slow at pasting. (using alt-space, edit, paste)

**Comment by wwiv** [comment] 2015-09-19 20:57
not crashing for me.. not sure why.

I get lots of these at the end...
-= No more lines, last line lost =-
/S to save

```
computers  are available,  one for  each phone  line. Another solution,
```

Since you have msvc, attaching the debugger to a crash and getting a stack trace would help.

**Comment by BloodStoneBBS** [comment] 2015-09-22 17:35
I can replicate this every time on Windows 7 b1586 but I am using SyncTerm.
Perhaps the bug is related to that?

No trouble at all when //load(ing) and posting a local text file. Only when pasting multiple lines of text via SyncTerm into an open message using the native message editor. Have not tried WWIVEdit on this install.

**Comment by BloodStoneBBS** [comment] 2015-09-22 17:42
Does not crash on 2008? I do get the  -= No more lines, last line lost =-  on both Windows 7 and 2008.
Just tried Windows 7 again - Crashed. Will look at the event logs when I can spend some time at the console tomorrow.

**Comment by BloodStoneBBS** [comment] 2015-09-22 18:05
Same Exception code as before:
Log Name:      Application
Source:        Application Error
Date:          9/21/2015 6:36:29 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WWIV5
Description:
Faulting application name: bbs.exe, version: 0.0.0.0, time stamp: 0x55ff97b6
Faulting module name: bbs.exe, version: 0.0.0.0, time stamp: 0x55ff97b6
Exception code: 0xc0000409
Fault offset: 0x000ef64a
Faulting process id: 0xb98
Faulting application start time: 0x01d0f4d6fb1dec41
Faulting application path: C:\wwiv\bbs.exe
Faulting module path: C:\wwiv\bbs.exe
Report Id: 5823a377-60ca-11e5-9a98-534e57000000
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-22T01:36:29.000000000Z" />
    <EventRecordID>8287</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WWIV5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55ff97b6</Data>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55ff97b6</Data>
    <Data>c0000409</Data>
    <Data>000ef64a</Data>
    <Data>b98</Data>
    <Data>01d0f4d6fb1dec41</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>5823a377-60ca-11e5-9a98-534e57000000</Data>
  </EventData>
</Event>

**Comment by wwiv** [comment] 2016-08-08 18:47
I've not been able to reproduce this, so nothing much I can do here.

If you run under visual studio's debugger and can get a stack trace that'd help, otherwise I'll close it as unable to reproduce.

**Closed as completed** 2016-08-08 18:47 UTC
Labels: bug, not reproducible, BBS
