### ISSUE TITLE
Subtypes and Network info for subs get scrambled around

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#489] opened 2015-12-19 19:34 UTC
When you install 1740+ the subtypes get scrambled around. I even tried it with 1741 as well. I had to re-enter all the subtypes all over again and went back to 1739. And then when i try to edit the sub info the program states: bbs terminated by exception : bad allocation.

**Comment by wwiv** [comment] 2015-12-19 20:51
If you see "gated" as the network type in the subs list, you have duplicate net info lines in data\subs.xtr.  open it up in a text editor and delete the duplicate lines that start with $

example:

Change:
$FILEnet NGABBSY 1 0 0
$FILEnet NGABBSY 1 0 0

to 

$FILEnet NGABBSY 1 0 0

**Comment by BloodStoneBBS** [comment] 2015-12-20 01:29
Having similar issue here - 
However, there are no duplicates in subs.xtr
There does appear to be missing information though.

**Comment by BloodStoneBBS** [comment] 2015-12-20 05:31
Rolled back subs.xtr and subs.dat and all looked just fine - until mail toss. after the network#.exe's ran, the subs list in BE are pooched again.
Rolled back to 1739, still pooches. Temporarily disabled my mail.bat file to prevent cross posts.
Example, subs 0-5 are not networked. Subtype list loses all gaps between 0 and the first subtype. Areas where there would normally be a gap is replaced with the next subtype in the list.
How it should look: 

![capture2](https://cloud.githubusercontent.com/assets/13243281/11916771/a12e165a-a69b-11e5-9145-5d4012bb441f.JPG)

How it does look:

![capture](https://cloud.githubusercontent.com/assets/13243281/11916764/dcf96316-a69a-11e5-9f46-7cd86cd19cc7.PNG)

**Comment by wwiv** [comment] 2015-12-20 16:53
Can you add screenshots or something showing me what pooched looks like?
I'll try to reproduce here. Sounds like a real bug I just need to figure
out where

**Comment by BloodStoneBBS** [comment] 2015-12-20 17:06
Screen shots of board edit above. Not certain how this impacts subs.def or .xtr but found messages from a usenet group  being delivered to a different sub.

Rolling subs.def & subs.xtr back a couple of days and the BBS back to 5.0 fixed this on my BBS's. Did not have time to try testing each retro build from 1739 down but it happens in 1739 and newer.

**Comment by wwiv** [comment] 2015-12-20 17:36
Do you have the subs.xtr from where it was broken? If so can you email it to me

**Comment by BloodStoneBBS** [comment] 2015-12-20 17:56
I do not but I can easily reproduce it. I'll do so on Manic Arcade and send you the files.

**Comment by BloodStoneBBS** [comment] 2015-12-20 18:10
Files sent. Does not appear to occur in 1735.

**Comment by BloodStoneBBS** [comment] 2015-12-20 18:16
Traced it to 1737.
But only after running my mail.bat file which also runs network1, network2 and /E

**Comment by wwiv** [comment] 2015-12-22 02:14
I think this is fixed as of 1750.  Please let me know if you see it happening again.

**Closed as completed by wwiv** 2015-12-22 02:14 UTC
Labels: bug
