### ISSUE TITLE
Pipe Macro Codes

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#898] opened 2016-11-27 22:05 UTC
Can;t get pipe macro codes to work in an ansi file.

**Comment by wwiv** [comment] 2016-11-28 00:12
here is my login.msg and it works
```
Today's date is: |@/
|@!
after pause.
```

**Comment by wwiv** [comment] 2016-11-28 00:14
I can't reproduce this, there is a menu command to disable MCI (aka macro)s.  Also make sure you have them enabled in wwiv.ini

Look for "ENABLE_MCI", it should be Y

**Comment by rdfig** [comment] 2016-11-28 00:50
I found a note that that says Enable pipes extra color and enable mci ARE always on in wwiv 5.0

 

I am running 5.2  2308

**Comment by wwiv** [comment] 2016-11-28 01:03
where is the node? I'm grepping though the readme files and don't see it.  Also it may not be true. Can you let me know where is this note, and also try setting ENABLE_MCI in wwiv.ini

**Comment by rdfig** [comment] 2016-11-28 01:22
Cannot find the menu command on to either disable or enable MCI

**Comment by rdfig** [comment] 2016-11-28 01:38
Here is my wwiv.ini with ENBALE_MCI=Y added.  Read below that to see the note I mentioned.

 

;=============================================================================
;
;                 WWIV Version 5.00 Initialization File
;
;              Lines begining with a semi-colon are ignored
;=============================================================================
;
; WWIV ID Block for default / common BBS settings.  This ID *must* appear as
; the first uncommented  line in the INI file.  See individual instance settings
; at the end of this file
;
[WWIV]
;
;=============================================================================
;                               SPAWN OPTIONS
;=============================================================================
;
; The various spawn options that may be used are:
;
; NOHUP        Doesn't check for hangup
; COMIO        Intercept DOS interrupts (Win32 Only)
; FOSSIL       Emulate the FOSSIL for DOS applications (Win32 Only)
; NETPROG      Tries to run program in network data dir first.
;
; Options can be combined like so:
;
; SPAWNOPTS[LOGON]=FOSSIL,NOHANGUP
;
; Valid locations that can have spawn options specified are:
;
; TIMED, NEWUSER, BEGINDAY, LOGON, LOGOFF ULCHK, PROT_SINGLE,
; PROT_BATCH, CHAT, ARCH_E, ARCH_V, ARCH_A, ARCH_D, ARCH_K, ARCH_T,
; NET_CMD1, NET_CMD2
;
; Values listed for lines commented out are the default settings.  Under
; normal conditions, you should not have to edit these settings.  If you
; have problems getting the stock spawn options to work properly with
; your supporting program, try adding COMIO.  These are
; the most commonly used settings.
;
; -----------------------------------------------------------------------------
;
;
; Event spawn options
;
;SPAWNOPT[TIMED]        =                               ; for timed event
;SPAWNOPT[NEWUSER]      =                               ; for newuser event
;SPAWNOPT[BEGINDAY]     =                               ; for beginday event
;SPAWNOPT[LOGON]        =                               ; for logon event
;SPAWNOPT[LOGOFF]       =                               ; for logoff event
;SPAWNOPT[ULCHK]        = NOHUP                         ; for upload event
;
; External program spawn options
;
;SPAWNOPT[PROT_SINGLE]  = NONE                          ; for single file xfers
;SPAWNOPT[PROT_BATCH]   = NONE                          ; for batch xfers
;SPAWNOPT[CHAT]         = NONE                          ; for wwivchat.exe
;
; Archiver spawn settings
;
;SPAWNOPT[ARCH_E]       =                         ; for extracting archives
;SPAWNOPT[ARCH_L]       =                         ; for viewing archives
;SPAWNOPT[ARCH_A]       =                         ; for adding to archives
;SPAWNOPT[ARCH_D]       =                         ; for deleting from archives
;SPAWNOPT[ARCH_K]       =                         ; for commenting archives
;SPAWNOPT[ARCH_T]       =                         ; for testing archives
;
;Network spawn options
;
; If NET_CLEANUP_CDM1 is defined below, the BBS will look for the file
; in the main BBS directory.  To run a file from the network data
; directory, add the NETPROG option.
;
;SPAWNOPT[NET_CMD1]     =                               ; for NET_CLEANUP_CMD1
;
; NET_CMD2 already has the NETPROG option set by default.
;
;SPAWNOPT[NET_CMD2]     = NETPROG                       ; for NET_CLEANUP_CMD2
;
; NETWORK is the setting to use when running network.exe
;
;SPAWNOPT[NETWORK]      =
;
;=============================================================================
;                               COLOR OPTIONS
;=============================================================================
;
; NOTE:  Although the BBS is capable of using over 90 color combinations,
; only the first ten may be set here.  The remaining colors are set from
; inside the BBS.
;
; Colors are selected numerically. To determine the value for a color, use the
; following chart:
;
;    0 = Black             8  = Dark Gray
;    1 = Blue              9  = Light Blue
;    2 = Green             10 = Light Green
;    3 = Cyan              11 = Light Cyan
;    4 = Red               12 = Light Red
;    5 = Magenta           13 = Light Magenta
;    6 = Brown             14 = Yellow
;    7 = Light Gray        15 = White
;
; Now, to calculate a color, you take the value for the background color and
; multiply by 16, then add it to the foreground color you wish. This will
; provide the value you should use for that color combination. Note that
: color values greater than 127 will result in blinking. In other words,
; you should probably restrict background colors to colors 0-7 above.
;
; An example: if you want to find the value for, say, bright yellow on magenta,
; it would be (5*16) + 14. This equates to (magenta * 16) + white.
;
; -----------------------------------------------------------------------------
NUCOLOR[0]     = 10
NUCOLOR[1]     = 11
NUCOLOR[2]     = 14
NUCOLOR[3]     = 13
NUCOLOR[4]     = 31
NUCOLOR[5]     = 10
NUCOLOR[6]     = 12
NUCOLOR[7]     = 11
NUCOLOR[8]     = 13
NUCOLOR[9]     = 10
NUCOLORBW[0]   = 12
NUCOLORBW[1]   = 15
NUCOLORBW[2]   = 15
NUCOLORBW[3]   = 15
NUCOLORBW[4]   = 112
NUCOLORBW[5]   = 15
NUCOLORBW[6]   = 15
NUCOLORBW[7]   = 11
NUCOLORBW[8]   = 15
NUCOLORBW[9]   = 12
;
; System Colors
;
TOPCOLOR               = 27                 ; for topscreen info
F1COLOR                = 10                 ; for F1 user editor
EDITLINECOLOR          = 31                 ; current field in F1
CHATSELCOLOR           = 11                 ; for selecting sysop
MSG_COLOR              = 10                 ; for color msgs
;
;=============================================================================
;                          EXTERNAL PROGRAM OPTIONS
;=============================================================================
;
;UPLOAD_CMD     =                           ; upload event
;BEGINDAY_CMD   =                           ; beginday even
;NEWUSER_CMD    =                           ; newuser event
;LOGON_CMD      =                           ; logon event
;
;
;=============================================================================
;                            NETWORK OPTIONS
;=============================================================================
;
;NET_CLEANUP_CMD1   =                       ; cleanup event 1
;NET_CLEANUP_CMD2   =                       ; cleanup event 2
NET_CALLOUT        = Y                      ; allow net callouts this instance
FIDO_PROCESS       = N                      ; process fido packets this instance
;
;=============================================================================
;                              SYSTEM FLAGS
;=============================================================================
; These settings enable or disable system features.  The most commonly
; used settings are already set for you.  You may want to experiment with
; various settings to tailor your system to your needs.
;
FORCE_FBACK            = Y                  ; force newusers to send fback
FORCE_NEWUSER          = Y                  ; force newusers to read NEWUSER.MSG
FORCE_SCAN             = N                  ; force user to scan sysop sub
FORCE_SCAN_SUBNUM      = N                  ; sub to force scan on
CHECK_DUP_PHONES       = N                  ; check newuser dupe phones
HANGUP_DUP_PHONES      = N                  ; hangup on newuser dupe phone
POSTTIME_COMPENS       = N                  ; compensate for time posting
SHOW_HIER              = Y                  ; show conf details in //je
IDZ_DESC               = Y                  ; 1st line of file_id.diz as descrip
SETLDATE               = N                  ; set file date on nscan
NEW_CHATSOUND          = Y                  ; use different chat alarm
SLASH_SZ               = Y                  ; enable "/s" and "/z" (Download Posts
READ_CD_IDZ            = N                  ; read file_id.diz from cdroms
FSED_EXT_DESC          = Y                  ; allow fsed for extended descriptions
FAST_TAG_RELIST        = Y                  ; don't show xfer dirs on tag relist
MAIL_PROMPT            = Y                  ; fancy mail prompt
SHOW_CITY_ST           = Y                  ; show city/state in laston info
LOCAL_SYSOP            = Y                  ; allow F-keys, space-f, etc
2WAY_CHAT              = Y                  ; 2-way local sysop chat
OFF_HOOK               = Y                  ; phone offhook when sysop on
LOG_DOWNLOADS          = N                  ; send SSM to uploader on file DL
CLOSE_XFER             = N                  ; disable transfer section
ALL_UL_TO_SYSOP        = Y                  ; all uploads go to sysop dir
NO_EASY_DL             = N                  ; Disable WWIV4*.* DL ignorng time,ratio
NEW_EXTRACT            = Y                  ; extended sysop-extract email/posts
FAST_SEARCH            = Y                  ; quick check of dup uploads
USER_REGISTRATION      = N                  ; allow account expirations
MSG_TAG                = Y                  ; sysop post/email taglines
CHAIN_REG              = N                  ; user sponsoring of chains
CAN_SAVE_SSM           = Y                  ; allow saving of SSMs
BEEP_CHAT              = Y                  ; alert sysop of chat requests
TWO_COLOR_CHAT         = Y                  ; dual color in non-2-way chat
ALLOW_ALIASES          = Y                  ; allow users to use aliases
USE_LIST               = Y                  ; use list.com to show sysoplog, etc
FREE_PHONE             = N                  ; allow any format phone #
LOGON_PHONE            = N                  ; check phone # at logon?
EXTENDED_USERINFO      = N                  ; enable addr, etc info in userrec
NEWUSER_MIN            = Y                  ; ask minimal new user information
ALLOW_CC_BCC           = Y                  ; allow CC: and BCC: for email?
THREAD_SUBS            = N                  ; activate threading message code
DISABLE_PD             = Y                  ; disable Pulldown menu support
TITLEBAR               = Y                  ; show user in console titlebar
ENABLE_PIPES             =Y
ENABLE_MCI             =Y
;
;!!!NOTE: ENABLE_PIPES, EXTRA_COLOR AND ENABLE_MCI are always on in wwiv 5.0
;
;=============================================================================
;                           SYSTEM TUNING PARAMETERS
;=============================================================================
;
MAIL_WHO_LEN           = 45                 ; max length of user name when
;                                           ; reading mail
;
ATTACH_DIR             = ATTACH             ; dir for email attachments
;
; AutoUserPurge purges the user base of all users who have not called in
; x days.  (Min Setting: 60) Users possessing the ADEL (bitwise:16)
; exemption are ignored.  USE CAUTION when setting this value as it
; could delete many dormant accounts.
;
;AUTO_USER_PURGE        = 60                ; Purge user base of users who
;                                           ; have not called within x days.
;NO_PURGE_SL            = 75                ; This SL and higher are skipped
;
MAX_BATCH              = 50                 ; max files in batch queue
MAX_EXTEND_LINES       = 20                 ; max extended description lines
MAX_CHAINS             = 50                 ; max chains allowed
MAX_GFILESEC           = 32                 ; max gfile sections allowed
;RATIO                 =                    ; ratio required
;
; ANSI Callout and WFC Options
;
CALLOUT_ANSI           = Y                  ; Use ANSI Callout Screen?
CALLOUT_COLOR          = 10                 ; Screen color
CALLOUT_HIGHLIGHT      = 30                 ; Highlight color
CALLOUT_NORMAL         = 15                 ; Normal color
CALLOUT_COLOR_TEXT     = 14                 ; Text Color
WFC_SCREEN             = Y                  ; Use ANSI WFC screen?
;                                           ; List sequentialy i.e. CDXYZ
SCREEN_SAVER_TIME      = 240                ; Screen saver invoke time (min.)

BEGINDAYNODENUMBER     = 1                  ; Node number to handle beginday
INTERNALZMODEM         = Y                  ; Set to N to disable internal Zmodem
EXEC_LOGSYNCFOSS       = N                  ; Create wwivsync.log when 
                                            ; executing a FOSSIL door.
EXEC_CHILDWAITTIME     = 500                ; Time to wait for the DOOR to load
                                            ; (used under Win9X)
NEW_SCAN_AT_LOGIN      = Y                  ; Ask the user to scan for new 
                                            ; messages when they log in.
USE_WWIVMAIL           = N                  ; Add WWIVMail to the //QWK menu
USE_INTERNAL_QWK       = Y                  ; Use internal QWK support
;
;=============================================================================
;                        TEMPORARY DIRECTORY SETTING
;=============================================================================
NUM_INSTANCES        = 4
TEMP_DIRECTORY       = temp%n
BATCH_DIRECTORY      = batch%n
;
;
;=============================================================================
;                           ASV / CALLBACK OPTIONS
;=============================================================================
; Auto Sysop Validation (ASV) and Callback Validation Settings allow you
; to tailor your system to automatically validate certain users and
; upgrade access levels based on the settings below.  By default, all
; options are OFF.  In most cases, only systems specializing in support
; will activate thes options.
;
USE_SIMPLE_ASV                  = N         ; Use Simple ASV?
;
; Simple ASV values
;
;SIMPLE_ASV[SL]                 = 75        ; SL to assign
;SIMPLE_ASV[DSL]                = 75        ; DSL to assign
;SIMPLE_ASV[EXEMPT]             = 16        ; Exemption to assign
;SIMPLE_ASV[AR]                 =           ; AR to assign
;SIMPLE_ASV[DAR]                =           ; DAR to assign
;SIMPLE_ASV[RESTRICT]           =           ; Restriction to assign
;
USE_ADVANCED_ASV                = N         ; Use Advanced ASV?
;
;Advanced ASV values correspond to auto-val settings in INIT minus one, e.g.
;Alt-[F1] auto-validation would be set to '0', Alt-[F2] to '1', etc.
;
;ADVANCED_ASV[REG_WWIV]         = 0         ; Alt-[F1] for Registered WWIV
;ADVANCED_ASV[NONREG_WWIV]      = 1         ; Alt-[F2] for Unregistered WWIV
;ADVANCED_ASV[NON_WWIV]         = 2         ; Alt-[F3] for Non-WWIV
;ADVANCED_ASV[COSYSOP]          = 3         ; Alt-[F4] for Co-Sysops
;
USE_CALLBACK                    = N         ; Use Callback Verification?
;
; CALLBACK values
;
;CALLBACK[SL]                 = 20          ; SL to assign
;CALLBACK[DSL]                = 20          ; DSL to assign
;CALLBACK[EXEMPT]             = 0           ; Exemption to assign
;CALLBACK[AR]                 =             ; AR to assign
;CALLBACK[DAR]                =             ; DAR to assign
;CALLBACK[RESTRICT]           = MA*N        ; Restriction to assign
;CALLBACK[FORCED]             = Y           ; Force Callback?
;CALLBACK[LONG_DISTANCE]      = Y           ; Make LD calls?
;CALLBACK[REPEAT]             = 3           ; Number or retries
;
USE_VOICE_VAL                 = N           ; Voice validation
;
;
;=============================================================================
;                        INSTANCE SPECIFIC OPTIONS
;=============================================================================
; There are only a very few settings that would or should be used for
; individual instances.  You may have an instance that does all network
; callouts or one that does all processing of Fido or other network mail.
; To define these instance specific settings, use an ID block [WWIV-<instance>]
; as follows:
;
; Instance #1
;[WWIV-1]
;NET_CALLOUT            = Y                 ; allow net callouts this instance
;FIDO_PROCESS           = N                 ; process fido packets this instance
;
; Instance #2
;[WWIV-2]
;NET_CALLOUT            = N                 ; allow net callouts this instance
;FIDO_PROCESS           = Y                 ; process fido packets this instance
;SCREEN_SAVER_TIME      = 120               ; Screen saver invoke time
;
;
;=============================================================================
;                         AVAILABLE COMPUTER TYPES
;=============================================================================
; These are the computer types offered to new users to choose from.
; You may add as many as you like or edit the existing entries.  They
; must be enumerated as shown.  Keep in mind that if you include too
; many types, they will scroll off the screen.
;
[CTYPES]
COMP_TYPE[1]  = IBM AT (80286/80386)
COMP_TYPE[2]  = IBM AT (80486/80586)
COMP_TYPE[3]  = AMD 80686 K6/K6-2
COMP_TYPE[4]  = Pentium
COMP_TYPE[5]  = Pentium MMX/Pro
COMP_TYPE[6]  = Pentium II
COMP_TYPE[7]  = Pentium III
COMP_TYPE[8]  = Alpha 500-550
COMP_TYPE[9]  = Sparc Workstation
COMP_TYPE[10] = Apple / MacIntosh
COMP_TYPE[11] = Commodore
COMP_TYPE[12] = Amiga
COMP_TYPE[13] = Atari
COMP_TYPE[14] = Others
;
;
;=============================================================================
;                         END OF BBS SPECIFIC SETTING
;=============================================================================
;  Many third party add-ons for WWIV use this file to maintain certain
;  settings.  You are advised to keep those settings below this point in
;  the file for readability and integrity.
;

**Comment by granitepenguin** [comment] 2016-11-28 01:49
Hmm... none of those are in the current wwivini.510 sample file that's part of the build archives.  That note doesn't exist, either.

It might be a good idea to verify all the available options and update the wwiv.ini sample file

**Comment by wwiv** [comment] 2016-11-28 04:36
Did adding ENABLE_MCI=Y to your wwiv.ini fix it?

**Comment by wwiv** [comment] 2016-11-28 04:37
good idea @granitepenguin , I'm sure some of these are not valid anymore (or ever)

**Comment by rdfig** [comment] 2016-11-28 15:40
No it did not.  Even using a macro of |@R didn’t produce user name,

**Comment by wwiv** [comment] 2016-11-29 04:14
ok, that's very strange... I don't have any ideas now. 

@BloodStoneBBS  Jimmy, can you add ENABLE_MCI to your bbs and see if it works for you? I'm wondering if there's something strange on My setup causing it to work.

Only thing I can suggest would be if you have visual studio community edition, compile it and run under a debugger, with a break point on the interpret function to see if it's invoked.  or step through bputch.

**Comment by BloodStoneBBS** [comment] 2016-11-29 05:32
Done – not sure how to test, I haven’t been following the thread very closely.

J..

**Comment by BloodStoneBBS** [comment] 2016-11-29 05:38
I read back a few messages –
Added:

Hello |@R
Today's date is: |@/

To login.msg (in gfiles)

End result:

Hello Jimmy Mac
Today's date is: 11/28/2016

**Comment by BloodStoneBBS** [comment] 2016-11-29 05:47
Sorry to bring unexpected news but disabling provides the same result. ENABLE_MCI appears to always be on in 5.2.0.2272 at least.

Commented out the line I added and I get the same results.

Thanks though, I hadn’t played with MCI but I can see now that I soon will!

**Comment by BloodStoneBBS** [comment] 2016-11-29 15:26
Ruben,  Which OS is your BBS running on? If Linux, could this be a problem with the case or path of the filenames?

**Comment by rdfig** [comment] 2016-11-29 15:29
Either way in 5.2.0.2311 it does not work

I put in my ansi main menu Hello |@R

And get Hello

**Comment by rdfig** [comment] 2016-11-29 15:30
Running on Windows 10, 32bit

**Comment by rdfig** [comment] 2016-11-29 15:43
Ok.  I added the MCI Macros where I wanted to and logged in as a regular user and they worked.  It does not work when I login as myself as the sysop.

**Comment by rdfig** [comment] 2016-11-29 15:45
Update..even ;logged in as a regular user it displays the macro, but if I go to T for file section and return I get blanks

**Comment by rdfig** [comment] 2016-11-29 15:50
Basically when the main.ans is displayed first time then the info is there.  Do anything else and return to the main.ans and the information is not displayed.

Tried it several times.  Could something in my setup be corrupt or just need updating?  I started off with wwiv 5.0 and now at 5.2

**Comment by rdfig** [comment] 2016-11-29 15:55
telnet to pb.darktech.org:1023 to see what it will do for you or not

**Comment by BloodStoneBBS** [comment] 2016-11-29 15:56
Windows 7 w32 here running 2314 now. Still works in both .msg and .ans files but I do not have any ansi code prior to the macro.

**Comment by rdfig** [comment] 2016-11-29 16:03
Updating now to 2304

**Comment by rdfig** [comment] 2016-11-29 16:03
2314

**Comment by BloodStoneBBS** [comment] 2016-11-29 16:42
At the office - Just attempted to telnet to pb.darktech.org:1023 but the connect failed. Will try again from home this evening.

meanwhile, try relaxing NTFS permissions on temp# folders. Windows 10 may be preventing the action.

**Comment by rdfig** [comment] 2016-11-29 18:20
The temp folders in the wwiv folders?  It’s relaxed open like a bordello

**Comment by BloodStoneBBS** [comment] 2016-11-29 20:49
I found that with 8.1 on up, I had to make sure to add "Everyone" to any folders that were to be accessed by script. I'm assuming that the pipe macro's get the username from the drop file in the temp# folder.

**Comment by rdfig** [comment] 2016-11-29 21:12
Understood and it does display the first time the user sees it at the Main menu.  But then they say go to Transfer menu and then back and it then doesn’t display the information Macro was supposed to provide.

**Comment by wwiv** [comment] 2016-11-30 02:36
This may work for you in 5.2.2315.

**Comment by rdfig** [comment] 2016-11-30 14:12
Sorry to report  I still have issues.

**Comment by wwiv** [comment] 2016-11-30 15:01
I'm out of ideas for you then, I removed the only place where it could have been turned off everywhere.  Hmm. I see one more, lemme try that one

**Comment by wwiv** [comment] 2016-11-30 15:48
ok 2318 should have that... let's see... now I'm out of ideas :(

**Comment by rdfig** [comment] 2016-12-01 00:11
Try now.  Just checked and find out firewall hasn’t been configured to let that port open.  It is now.

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by BloodStoneBBS** [comment] 2016-12-01 00:58
Yep – I see what you mean.
With the PIPES in the menu, they do display on first load but then are gone after selecting another menu such as the transfer menu. Once you go back to the main menu, the pipes are broken.

Edit: I cannot replicate this on my Windows 7.

--

Try now. Just checked and find out firewall hasn’t been configured to let that port open. It is now.

**Comment by rdfig** [comment] 2016-12-01 02:39
Interesting note.  Yes when coming back to messages it still displays the code.  When you go to transfer menu and back to main, the info disappears.

But if you go read a message and return, the code is displayed.

 

Have you tried duplicating this on your system, assuming you have the latest 5.2 2319

**Comment by wwiv** [comment] 2016-12-01 06:23
just pushed a fix. the menu prompts were disabling the mci codes.

**Comment by rdfig** [comment] 2016-12-01 13:53
That did it.  Also played with the scrolling prompt.  It works great.  But couldn’t respond to a message.

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by wwiv** [comment] 2016-12-01 14:15
Yup. I'll add in a w p commands tonight if I can. It'll take a while to get
functional :-)

**Comment by rdfig** [comment] 2016-12-01 14:18
No problem in waiting.  Thanks for all your hard work and long hours.

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Closed as completed** 2016-12-01 18:06 UTC
Labels: bug, not reproducible, BBS
